-- ============================================================================
-- GREETING MODULE - DATABASE SCHEMA
-- ============================================================================
-- This schema is AUTO-GENERATED by Hibernate based on the Greeting entity
-- No need to run this manually - provided for reference only
-- The table is created automatically when the application starts
-- ============================================================================

-- Database Selection
-- Local:   USE tanishq;
-- Preprod: USE selfie_preprod;
-- Prod:    USE selfie_prod;

-- ============================================================================
-- TABLE: greetings
-- ============================================================================
-- Purpose: Store video greeting card metadata
-- Auto-created by: Hibernate (spring.jpa.hibernate.ddl-auto=update)
-- ============================================================================

CREATE TABLE IF NOT EXISTS `greetings` (
    -- Primary Key
    `id` BIGINT NOT NULL AUTO_INCREMENT,

    -- Unique Identifier (e.g., "GREETING_1738318234567")
    `unique_id` VARCHAR(255) DEFAULT NULL,

    -- Sender Information
    `greeting_text` VARCHAR(255) DEFAULT NULL COMMENT 'Sender name',
    `phone` VARCHAR(255) DEFAULT NULL COMMENT 'Sender phone (optional)',
    `message` TEXT DEFAULT NULL COMMENT 'Personal message from sender',

    -- QR Code Data (Base64 encoded PNG image)
    `qr_code_data` LONGTEXT DEFAULT NULL COMMENT 'Base64 encoded QR code image',

    -- Video File URL (S3 or local file path)
    -- Note: Column name is misleading - it stores URL, not Google Drive file ID
    `drive_file_id` VARCHAR(255) DEFAULT NULL COMMENT 'Video URL (S3 or local path)',

    -- Metadata
    `created_at` DATETIME DEFAULT NULL COMMENT 'Timestamp when greeting was created',
    `uploaded` TINYINT(1) DEFAULT 0 COMMENT 'Flag: has video been uploaded? 0=no, 1=yes',

    -- Constraints
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_unique_id` (`unique_id`),
    KEY `idx_uploaded` (`uploaded`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Video greeting cards - stores metadata and video URLs';

-- ============================================================================
-- SAMPLE DATA (FOR TESTING)
-- ============================================================================

-- INSERT INTO greetings (unique_id, greeting_text, phone, message, uploaded, created_at) VALUES
-- ('GREETING_1738318234567', 'John Doe', '9876543210', 'Happy Birthday! Wishing you all the best!', 0, NOW()),
-- ('GREETING_1738318234568', 'Jane Smith', '9876543211', 'Congratulations on your success!', 1, NOW());

-- ============================================================================
-- USEFUL QUERIES
-- ============================================================================

-- Check if table exists
-- SHOW TABLES LIKE 'greetings';

-- View table structure
-- DESC greetings;

-- View detailed column information
-- SELECT
--     COLUMN_NAME,
--     DATA_TYPE,
--     CHARACTER_MAXIMUM_LENGTH,
--     IS_NULLABLE,
--     COLUMN_DEFAULT,
--     COLUMN_COMMENT
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_SCHEMA = DATABASE()
--   AND TABLE_NAME = 'greetings'
-- ORDER BY ORDINAL_POSITION;

-- Count total greetings
-- SELECT COUNT(*) as total_greetings FROM greetings;

-- Count uploaded vs pending
-- SELECT
--     CASE WHEN uploaded = 1 THEN 'Uploaded' ELSE 'Pending' END as status,
--     COUNT(*) as count
-- FROM greetings
-- GROUP BY uploaded;

-- View recent greetings
-- SELECT
--     unique_id,
--     greeting_text,
--     CASE WHEN uploaded = 1 THEN 'Yes' ELSE 'No' END as video_uploaded,
--     created_at
-- FROM greetings
-- ORDER BY created_at DESC
-- LIMIT 20;

-- Find greeting by unique ID
-- SELECT * FROM greetings WHERE unique_id = 'GREETING_1738318234567';

-- View all uploaded greetings with video URLs
-- SELECT
--     unique_id,
--     greeting_text,
--     message,
--     drive_file_id as video_url,
--     created_at
-- FROM greetings
-- WHERE uploaded = 1
-- ORDER BY created_at DESC;

-- Clean up old greetings (older than 90 days)
-- DELETE FROM greetings
-- WHERE created_at < DATE_SUB(NOW(), INTERVAL 90 DAY);

-- ============================================================================
-- MAINTENANCE QUERIES
-- ============================================================================

-- Backup greetings table
-- CREATE TABLE greetings_backup AS SELECT * FROM greetings;

-- Restore from backup
-- TRUNCATE TABLE greetings;
-- INSERT INTO greetings SELECT * FROM greetings_backup;

-- Optimize table
-- OPTIMIZE TABLE greetings;

-- Analyze table
-- ANALYZE TABLE greetings;

-- Check table size
-- SELECT
--     table_name,
--     ROUND((data_length + index_length) / 1024 / 1024, 2) AS 'Size (MB)',
--     table_rows
-- FROM information_schema.TABLES
-- WHERE table_schema = DATABASE()
--   AND table_name = 'greetings';

-- ============================================================================
-- MIGRATION NOTES
-- ============================================================================

-- If migrating from Google Sheets version to MySQL version:
--
-- 1. Export data from Google Sheets
-- 2. Transform columns:
--    - Column A (qrId) → unique_id
--    - Column B (status) → uploaded (PENDING=0, UPLOADED=1)
--    - Column C (videoFileId) → drive_file_id
--    - Column F (name) → greeting_text
--    - Column G (message) → message
--    - Column E (submissionTimestamp) → created_at
--
-- 3. Import using INSERT statements or CSV import
--
-- Example transformation:
-- INSERT INTO greetings (unique_id, greeting_text, message, drive_file_id, uploaded, created_at)
-- SELECT
--     qrId,
--     name,
--     message,
--     videoFileId,
--     CASE WHEN status = 'UPLOADED' THEN 1 ELSE 0 END,
--     STR_TO_DATE(submissionTimestamp, '%Y-%m-%d %H:%i:%s')
-- FROM temp_google_sheets_data;

-- ============================================================================
-- TROUBLESHOOTING
-- ============================================================================

-- If table not created automatically:
-- 1. Check application.properties: spring.jpa.hibernate.ddl-auto=update
-- 2. Check database connection in application logs
-- 3. Verify Greeting entity is scanned by Spring Boot
-- 4. Manually create table using schema above if needed

-- Check Hibernate is managing the table:
-- SELECT * FROM information_schema.tables
-- WHERE table_schema = DATABASE()
--   AND table_name = 'greetings';

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================

